name: ci
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          # check the spec types
          build: npm run lint
          # start the application before running Cypress
          start: npm run start-quiet
          # since some of the tests should fail, we can use cypress-expect
          # to verify they indeed fail
          # https://github.com/bahmutov/cypress-expect
          command: npx cypress-expect run --record --tag ci --expect cypress/expected.json
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
